environment:
  global:
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C C:\\project\\run_with_cmd.cmd"

  matrix:
    # Preinstalled Python versions
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "64"

    # Python 2.6.6 is the only Python 2.6 version that can be installed
    # without installing extra dependencies. See:
    # https://github.com/ogrisel/python-appveyor-demo/issues/10
    # https://github.com/pypa/pip/issues/2494
    - PYTHON: "C:\\Python266"
      PYTHON_VERSION: "2.6.6"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python266"
      PYTHON_VERSION: "2.6.6"
      PYTHON_ARCH: "64"

build: false  # Not a C# project, build stuff at the test step instead.
clone_folder: c:\\project

install:
  # First, download and install some files which help with the
  # build/compile process
  - ps: Invoke-WebRequest https://raw.githubusercontent.com/pypa/python-packaging-user-guide/master/source/code/run_with_compiler.cmd -OutFile C:\\project\\run_with_cmd.cmd
  - ps: Invoke-WebRequest https://raw.githubusercontent.com/pypa/python-packaging-user-guide/master/source/code/install.ps1 -OutFile C:\\project\\install.ps1

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & C:\\project\\install.ps1 }

  # Install some additional Python modules which will be required by
  # the tests.  Oddly, there are somtimes issues in AppVeyor and/or Windows
  # if these are installed from the setup.py.
  - "%PYTHON%\\Scripts\\pip.exe install setuptools coverage wheel --upgrade"

test_script:
  # Build the compiled extension and run the project tests
  - ps: cd C:\\project
  - "%WITH_COMPILER% %PYTHON%\\Scripts\\coverage.exe run setup.py test"
  - "%PYTHON%\\Scripts\\coverage.exe report"

after_test:
  - "%WITH_COMPILER% %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
